import { IColumnProps } from 'devextreme-react/data-grid';
import { resStatusSource } from '@/app/lib/store';

export const columns: IColumnProps[] = [
  { dataField: 'RezId', dataType: 'number', caption: 'Res.ID', width: 70, fixed: true, allowResizing: false },
  {
    dataField: 'RezDurum',
    dataType: 'number',
    caption: 'Res.Status',
    width: 76,
    minWidth: 76,
    lookup: { dataSource: resStatusSource, valueExpr: 'k', displayExpr: 'v' },
  },
  { dataField: 'KirmiziVarWeb', dataType: 'boolean', caption: 'Blue', width: 60, minWidth: 60 },
  { dataField: 'KalanSure', dataType: 'number', caption: 'Remaining Time', width: 100, minWidth: 100 },
  { dataField: 'Durum', dataType: 'number', caption: 'Load Status', width: 133, minWidth: 133, calculateDisplayValue: 'DurumName' },
  { dataField: 'DurumNot', dataType: 'string', caption: 'Status Note', width: 123, minWidth: 123 },
  { dataField: 'YurtDisiFirmaId', dataType: 'number', caption: 'Shipper', width: 110, minWidth: 110, calculateDisplayValue: 'YurtDisiFirmaName' },
  { dataField: 'YurtIciFirmaId', dataType: 'number', caption: 'Consignee', width: 110, minWidth: 110, calculateDisplayValue: 'YurtIciFirmaName' },
  { dataField: 'SOStatus', dataType: 'number', caption: 'SO Status', width: 133, minWidth: 133 },
  { dataField: 'Hacim', dataType: 'number', caption: 'Volume', width: 50, minWidth: 50, format: '#,##0.000' },
  { dataField: 'KapAdet', dataType: 'number', caption: 'Package', width: 40, minWidth: 40, format: '#,##0' },
  { dataField: 'Kilo', dataType: 'number', caption: 'Weight', width: 55, minWidth: 55, format: '#,##0.00' },
  { dataField: 'Istif', dataType: 'boolean', caption: 'Stacking Status', width: 76, minWidth: 76 },
  { dataField: 'CikisYeriId', dataType: 'number', caption: 'POE', width: 90, minWidth: 90, calculateDisplayValue: 'CikisYeriName' },
  { dataField: 'CikisLimaniId', dataType: 'number', caption: 'POL', width: 90, minWidth: 90, calculateDisplayValue: 'CikisLimaniName' },
  { dataField: 'VarisYeriId', dataType: 'number', caption: 'POD', width: 90, minWidth: 90, calculateDisplayValue: 'VarisYeriName' },
  { dataField: 'YukHazirTarihi', dataType: 'date', caption: 'Ready Date', width: 68, minWidth: 68, format: 'dd.MM.yyyy' },
  { dataField: 'PickUpTarihi', dataType: 'date', caption: 'Pick Up Date', width: 68, minWidth: 68, format: 'dd.MM.yyyy' },
  { dataField: 'BargePortSailingDate', dataType: 'date', caption: 'Barge Port Sailing', width: 68, minWidth: 68, format: 'dd.MM.yyyy' },
  { dataField: 'YDAntrepoTarih', dataType: 'date', caption: 'WH Arrival Date', width: 68, minWidth: 68, format: 'dd.MM.yyyy' },
  { dataField: 'CutOffTarihi', dataType: 'date', caption: 'Document Cut-Off', width: 68, minWidth: 68, format: 'dd.MM.yyyy' },
  { dataField: 'ArmatorCutOff', dataType: 'date', caption: 'VGM Cut-Off', width: 68, minWidth: 68, format: 'dd.MM.yyyy' },
  { dataField: 'MuhtemelCikisTarihi', dataType: 'date', caption: 'ETD', width: 68, minWidth: 68, format: 'dd.MM.yyyy' },
  { dataField: 'MuhtemelVarisTarihi', dataType: 'date', caption: 'ETA', width: 68, minWidth: 68, format: 'dd.MM.yyyy' },
  { dataField: 'TeslimSekli', dataType: 'string', caption: 'Incoterms', width: 60, minWidth: 60, calculateDisplayValue: 'TeslimSekli' },
  { dataField: 'HatId', dataType: 'number', caption: 'Line', width: 110, minWidth: 110, calculateDisplayValue: 'HatName' },
  { dataField: 'ArakonsimentoNo', dataType: 'string', caption: 'HBL No', width: 113, minWidth: 113 },
  { dataField: 'SabitNot', dataType: 'string', caption: 'HBL Type', width: 68, minWidth: 68 },
  { dataField: 'AnaKonsimentoNo', dataType: 'string', caption: 'MBL No', width: 113, minWidth: 113 },
  { dataField: 'KonteynerList', dataType: 'string', caption: 'Container Info', width: 123, minWidth: 123 },
  { dataField: 'GemiAdi', dataType: 'string', caption: 'Vessel Name', width: 140, minWidth: 140 },
  { dataField: 'GondericiOdemeBekliyor', dataType: 'boolean', caption: 'Shipper waiting for payment', width: 68, minWidth: 68 },
  { dataField: 'AcenteLocalMasrafBekliyor', dataType: 'boolean', caption: 'Agency expects local charges', width: 68, minWidth: 68 },
  { dataField: 'MalinCinsi', dataType: 'string', caption: 'Goods Desc.', width: 120, minWidth: 120 },
  { dataField: 'KayitTarih', dataType: 'datetime', caption: 'Rec.Date', width: 116, minWidth: 116, format: 'dd.MM.yyyy HH:mm:ss' },
  { dataField: 'GuncellemeKullanici', dataType: 'string', caption: 'Last Edit User', width: 100, minWidth: 100 },
  { dataField: 'GuncellemeTarih', dataType: 'datetime', caption: 'Last Edit Date', width: 116, minWidth: 116, format: 'dd.MM.yyyy HH:mm:ss' },
  { dataField: 'KonsolNo', dataType: 'string', caption: 'Console No', width: 66, minWidth: 66 },
  { dataField: 'KonsolPlan', dataType: 'string', caption: 'Console Plan', width: 66, minWidth: 66 },
  { dataField: 'AktarmaGemiAdi', dataType: 'string', caption: 'Trn. Vessel', visible: false, showInColumnChooser: false },
];
